services:
  birthday-texter:
    build:
      context: .
      dockerfile: dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      TZ: Europe/Kyiv
      TELEGRAM_API_ID: ${TELEGRAM_API_ID:-}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH:-}
    volumes:
      - ./data:/app/data
